# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-28 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe5\x86\x85\xe5\xae\xb9')),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[(0, b'\xe4\xb8\xad\xe6\x96\x87'), (1, b'\xe8\x8b\xb1\xe6\x96\x87')], default=b'python', max_length=100, verbose_name=b'\xe8\xaf\xad\xe8\xa8\x80')),
                ('style', models.CharField(choices=[(0, b'\xe6\x95\xa3\xe6\x96\x87'), (1, b'\xe8\xaf\x97\xe6\xad\x8c'), (1, b'\xe6\x8a\x80\xe6\x9c\xaf\xe5\x8d\x9a\xe6\x96\x87')], default=b'friendly', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
